[package]
name = "cache_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
hashring = "0.3.3"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
siphasher = "0.3.1"